
```{r}
library(plotly)
```

```{r}
library(ggplot2)
```

```{r}
p <- ggplot(data=mpg, aes(x=displ, y=hwy, col=drv)) + geom_point()
```

```{r}
p
```

```{r}
ggplotly(p)
```

```{r}
p <- ggplot(data = diamonds, aes(x=cut, fill=clarity))+geom_bar(position="dodge")
ggplotly(p)
```

```{r}
install.packages("dygraphs")
```

```{r}
mpg
```


```{r}
mpg <- as.data.frame(ggplot2::mpg)
library(dplyr)
mpg_diff <- mpg %>% select(class, cty) %>% filter(class %in% c("compact","suv"))
```

```{r}
head(mpg_diff)
```

```{r}
t.test(data = mpg_diff, cty~class, var.equal = T)
```

```{r}
economics <- as.data.frame(ggplot2::economics)
cor.test(economics$unemploy, economics$pce)
```

```{r}
car_cor <- cor(mtcars)
round(car_cor,2)
```

```{r}
install.packages("corrplot")
```

```{r}
library(corrplot)
```
```{r}
corrplot(car_cor)
```

```{r}
corrplot(car_cor,method = "number")
```

```{r}
col <- colorRampPalette(c("#BB4444","#EE9988","#FFFFFF","#77AADD","#4477AA"))
```

```{r}
corrplot(car_cor, 
         method = "color",
         col = col(200),
         type = "lower",
         order = "hclust",
         addCoef.col = "black",
         tl.col = "black",
         tl.srt = 45,
         diag = F)
```

```{r}
var1 <- c(1,2,3,1,2)
var2 <- factor(c(1,2,3,1,2))
```

```{r}
var1
```
```{r}
var2
```
```{r}
var1+2
```
```{r}
var2+2
```

```{r}
class(var1)
```
```{r}
class(var2)
```

```{r}
levels(var1)
```
```{r}
levels(var2)
```

```{r}
var3 <- c("a","b","b","c")
var4 <- factor(c("a","b","b","c"))
```

```{r}
var3
```
```{r}
var4
```

```{r}
class(var3)
```

```{r}
x1 <- data.frame(var1 = c(1,2,3), var2 = c("a","b","c"))
x1
```

```{r}
x2 <- matrix(c(1:12),ncol = 2)
x2
```

```{r}
x3 <- array(1:20, dim = c(2,5,2))
x3
```

```{r}
x4 <- list(f1 = a, f2 = x1, f3 = x2, f4 = x3)
```

```{r}
x4
```

```{r}

```

