```{r}
health <- read.csv("C:/Users/wonjun/Desktop/Rproject/data/back/health2.csv", stringsAsFactors = TRUE)
```

```{r}
t.test(health$survival,health$sex)
```


```{r}
health_cor<-cor(health)
```

```{r}
round(health_cor,2)
```


```{r}
library(corrplot)
```

```{r}
model <- lm(heart_disease~.,data=health)
```

```{r}
summary(model)
```

```{r}
cor.test(health$liver_disease,health$sex)
```

```{r}
cor.test(health$survival,health$BMI)
```

```{r}
cor.test(health$survival,health$heart_disease)
```

```{r}
model2<-lm(age~.,data=health)
```

```{r}
summary(model2)
```

```{r}
cor.test(health$age,health$heart_disease)
```

```{r}
cor.test(health$hypertension,health$survival)


```

```{r}
cor.test(health$age,health$hypertension)
```

```{r}
cor.test(health$age,health$diabetes)
```

```{r}
cor.test(health$age,health$other_diseases)
```

```{r}
model2_1<-lm(heart_disease~.,data=health)
```

```{r}
summary(model2_1)
```

```{r}
cor.test(health$heart_disease,health$age)
```

```{r}
cor.test(health$heart_disease,health$hypertension)
```

```{r}
model2_2<-lm(hypertension~.,data=health)
```

```{r}
summary(model2_2)
```

```{r}
cor.test(health$hypertension,health$other)
```

```{r}
model3_1<-lm(BMI~.,data=health)
```

```{r}
summary(model3_1)
```

```{r}
cor.test(health$BMI,health$other_diseases)
```

```{r}
model4_1<-lm(diabetes~.,data=health)
```

```{r}
summary(model4_1)
```

```{r}
cor.test(health$diabetes, health$kidney_disease)
```

```{r}
cancer <- read.csv("C:/Users/wonjun/Desktop/Rproject/data/back/cancer2.csv", stringsAsFactors = TRUE)
```

```{r}
model5 <- lm(survival~.,data=cancer)
```

```{r}
summary(model5)
```

```{r}
cor.test(cancer$survival, cancer$lymphatic_invasion)
```

```{r}
model6 <- lm(CEA~.,data=cancer)
```

```{r}
summary(model6)
```

```{r}
cor.test(cancer$CEA, cancer$vascular_invasion)
```

```{r}
model7 <- lm(ASA~.,data=cancer)
```

```{r}
summary(model7)
```

```{r}
cor.test(cancer$ASA, cancer$neural_invasion)
```

```{r}
model8 <- lm(T~.,data=cancer)
```

```{r}
summary(model8)
```

```{r}
cor.test(cancer$T, cancer$lymphatic_invasion)
```

```{r}
model9 <- lm(N~.,data=cancer)
```

```{r}
summary(model9)
```

```{r}
cor.test(cancer$N, cancer$M)
```

```{r}
model10 <- lm(M~.,data=cancer)
```

```{r}
summary(model10)
```

```{r}
cor.test(health$hypertension,health$lung_disease)
```

```{r}
cor.test(cancer$T, cancer$neural_invasion, method="pearson")
```

```{r}
model11 <- lm(poorly_diff~.,data=cancer)
```

```{r}
summary(model11)
```

```{r}
cor.test(cancer$poorly_diff, cancer$lymphatic_invasion)
```

```{r}
model12 <- lm(lymphatic_invasion~.,data=cancer)
```

```{r}
summary(model12)
```

```{r}
cor.test(cancer$ASA, cancer$neural_invasion)
```

```{r}
model13 <- lm(neural_invasion~.,data=cancer)
```

```{r}
summary(model13)
```

```{r}
cor.test(cancer$neural_invasion, cancer$vascular_invasion)
```

```{r}
model11 <- lm(poorly_diff~.,data=cancer)
```

```{r}
summary(model11)
```

```{r}

```

```{r}

```

